Repository juan656/web-dev-projects, pull requests merged in 2022-10, with the labels that each got.

#1 Encryption Decryption
  Encryption Decryption/.DS_Store
  Encryption Decryption/LICENSE
  Encryption Decryption/README.md
  Encryption Decryption/main.cs
  README.md
Labels: good first issue, hacktoberfest-accepted

#2 Django react boilerplate
  .DS_Store
  Django-React-Postgres-Authentication-Boilerplate/README.md
  Django-React-Postgres-Authentication-Boilerplate/backend/.gitignore
  Django-React-Postgres-Authentication-Boilerplate/backend/api/__init__.py
  Django-React-Postgres-Authentication-Boilerplate/backend/api/admin.py
  Django-React-Postgres-Authentication-Boilerplate/backend/api/apps.py
  Django-React-Postgres-Authentication-Boilerplate/backend/api/migrations/__init__.py
  Django-React-Postgres-Authentication-Boilerplate/backend/api/models.py
  Django-React-Postgres-Authentication-Boilerplate/backend/api/serializer.py
  Django-React-Postgres-Authentication-Boilerplate/backend/api/tests.py
  Django-React-Postgres-Authentication-Boilerplate/backend/api/urls.py
  Django-React-Postgres-Authentication-Boilerplate/backend/api/views.py
  Django-React-Postgres-Authentication-Boilerplate/backend/backend/__init__.py
  Django-React-Postgres-Authentication-Boilerplate/backend/backend/asgi.py
  Django-React-Postgres-Authentication-Boilerplate/backend/backend/settings.py
  Django-React-Postgres-Authentication-Boilerplate/backend/backend/urls.py
  Django-React-Postgres-Authentication-Boilerplate/backend/backend/wsgi.py
  Django-React-Postgres-Authentication-Boilerplate/backend/manage.py
  Django-React-Postgres-Authentication-Boilerplate/backend/requirements.txt
  Django-React-Postgres-Authentication-Boilerplate/frontend/.gitignore
  Django-React-Postgres-Authentication-Boilerplate/frontend/package-lock.json
  Django-React-Postgres-Authentication-Boilerplate/frontend/package.json
  Django-React-Postgres-Authentication-Boilerplate/frontend/public/favicon.ico
  Django-React-Postgres-Authentication-Boilerplate/frontend/public/index.html
  Django-React-Postgres-Authentication-Boilerplate/frontend/public/logo192.png
  Django-React-Postgres-Authentication-Boilerplate/frontend/public/logo512.png
  Django-React-Postgres-Authentication-Boilerplate/frontend/public/manifest.json
  Django-React-Postgres-Authentication-Boilerplate/frontend/public/robots.txt
  Django-React-Postgres-Authentication-Boilerplate/frontend/src/App.js
  Django-React-Postgres-Authentication-Boilerplate/frontend/src/components/Footer.js
  Django-React-Postgres-Authentication-Boilerplate/frontend/src/components/Navbar.js
  Django-React-Postgres-Authentication-Boilerplate/frontend/src/components/UserInfo.js
  Django-React-Postgres-Authentication-Boilerplate/frontend/src/context/AuthContext.js
  Django-React-Postgres-Authentication-Boilerplate/frontend/src/index.css
  Django-React-Postgres-Authentication-Boilerplate/frontend/src/index.js
  Django-React-Postgres-Authentication-Boilerplate/frontend/src/utils/PrivateRoute.js
  Django-React-Postgres-Authentication-Boilerplate/frontend/src/utils/useAxios.js
  Django-React-Postgres-Authentication-Boilerplate/frontend/src/views/ProtectedPage.js
  Django-React-Postgres-Authentication-Boilerplate/frontend/src/views/homePage.js
  Django-React-Postgres-Authentication-Boilerplate/frontend/src/views/loginPage.js
  Django-React-Postgres-Authentication-Boilerplate/frontend/src/views/registerPage.js
  sphere-os/Kernel.cs
  sphere-os/LICENSE
  sphere-os/README.md
  sphere-os/commands/cd.cs
  sphere-os/commands/clear.cs
  sphere-os/commands/command.cs
  sphere-os/commands/echo.cs
  sphere-os/commands/ls.cs
  sphere-os/commands/mkdir.cs
  sphere-os/commands/mkfile.cs
  sphere-os/commands/shutdown.cs
  sphere-os/commands/write.cs
  sphere-os/contributing.txt
  sphere-os/filesystem/fs.cs
  sphere-os/sphere-os.csproj
  sphere-os/sphere-os.sln
Labels: hacktoberfest-accepted

#3 notetaker
  .DS_Store
  notetaker/README.md
  notetaker/notes-app/Addnote.js
  notetaker/notes-app/ListNotes.js
  notetaker/notes-app/ReadNote.js
  notetaker/notes-app/Removenote.js
  notetaker/notes-app/app.js
  notetaker/notes-app/notes.json
  notetaker/notes-app/package-lock.json
  notetaker/notes-app/package.json
Labels: hacktoberfest-accepted

#4 ginit
  .DS_Store
  ginit/LICENSE
  ginit/README.md
  ginit/index.js
  ginit/lib/files.js
  ginit/lib/github.js
  ginit/lib/inquirer.js
  ginit/lib/repo.js
  ginit/package-lock.json
  ginit/package.json
Labels: hacktoberfest-accepted

#5 upload custom linktree page
  custom-linktree-page/README.md
  custom-linktree-page/assets/css/style.css
  custom-linktree-page/assets/img/boy.png
  custom-linktree-page/index.html
Labels: hacktoberfest-accepted

#6 upload simple js calculator
  simple-js-calculator/index.html
  simple-js-calculator/script.js
  simple-js-calculator/styles.css
Labels: hacktoberfest-accepted

#7 add todo site
  todo-site/index.html
  todo-site/script.js
  todo-site/style.css
Labels: enhancement, hacktoberfest-accepted

#8 upload digital clock files
  digital-clock/index.html
  digital-clock/main.css
Labels: hacktoberfest-accepted

#9 upload contact form
  Contact Us Form/contactform.html
  Contact Us Form/style.css
Labels: hacktobefest-approved, hacktoberfest, hacktoberfest-accepted
